// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrace potřebují přímé spojení do Postgresu — přes connection
    // pooler (např. Neon "pooled" connection string / PgBouncer) se
    // spolehlivě nezíská advisory lock, který `prisma migrate` používá,
    // a migrace pak spadne na timeoutu. `DIRECT_URL` proto míří na
    // nepoolovanou connection string; appka za běhu (src/lib/prisma.ts)
    // pořád používá poolovanou `DATABASE_URL` beze změny. Lokálně stačí
    // jen `DATABASE_URL` (lokální Postgres žádný pooler nemá).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
